service:
  type: ClusterIP
  port: 80

deployment:
  image: client-service:0.1.0
  replicas: 1
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits: 
      memory: "128Mi"
      cpu: "500m"
