apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: jena-daemonset
spec:
  selector:
    matchLabels:
      name: jena
  template:
    metadata:
      labels:
        name: jena
    spec:
      containers:
      - name: jena
        image: stain/jena-fuseki:latest
        ports:
        - containerPort: 3030

