apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    app: {{ include "service.fullname" . }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ include "service.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "service.fullname" . }}
    spec:
      containers:
        - name: coordination-service
          image: {{ .Values.deployment.image }}
          env:
            - name: SERVICE_PORT
              value: {{ .Values.deployment.port | quote }}
          ports:
            - containerPort: {{ .Values.deployment.port }}
          livenessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.deployment.port }}
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /sys_status
              port: {{ .Values.deployment.port }}
            initialDelaySeconds: 15
            periodSeconds: 20
          startupProbe:
            httpGet:
              path: /ping
              port: {{ .Values.deployment.port }}
{{- if .Values.deployment.resources }}
          resources:
            {{- toYaml $.Values.deployment.resources | nindent 12 }}
{{- end }}
