---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "service.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: coordination_service
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}

