kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prescoreplugin-idmg-scheduler-clusterrole
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - create
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - endpoints
      - events
    verbs:
      - create
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - delete
      - get
      - list
      - watch
      - update
  - apiGroups:
      - ""
    resources:
      - bindings
      - pods/binding
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - pods/status
    verbs:
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - replicationcontrollers
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
      - extensions
    resources:
      - replicasets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
      - persistentvolumes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "storage.k8s.io"
    resources:
      - storageclasses
      - csinodes
      - csistoragecapacities
      - csidrivers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - leases
    verbs:
      - create
      - get
      - list
      - update
  - apiGroups:
      - "events.k8s.io"
    resources:
      - events
    verbs:
      - create
      - patch
      - update
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prescoreplugin-idmg-scheduler-sa
  namespace: idmg-scheduler
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prescoreplugin-idmg-scheduler-clusterrolebinding
  namespace: idmg-scheduler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prescoreplugin-idmg-scheduler-clusterrole
subjects:
  - kind: ServiceAccount
    name: prescoreplugin-idmg-scheduler-sa
    namespace: idmg-scheduler
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
  namespace: idmg-scheduler
data:
  prescore-scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
      leaseDuration: 15s
      renewDeadline: 10s
      resourceName: prescoreplugin
      resourceNamespace: idmg-scheduler
      retryPeriod: 2s
    profiles:
      - schedulerName: default-scheduler
        plugins:
          preScore:
            enabled:
              - name: prescoreplugin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prescoreplugin
  namespace: idmg-scheduler
  labels:
    app.kubernetes.io/name: prescoreplugin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prescoreplugin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prescoreplugin
    spec:
      serviceAccountName: prescoreplugin-idmg-scheduler-sa
      priorityClassName: system-cluster-critical
      volumes:
        - name: scheduler-config
          configMap:
            name: scheduler-config
      containers:
        - name: prescoreplugin
          image: idmg/prescoreplugin
          imagePullPolicy: Always
          command:
            - prescoreplugin
            - --config=/etc/kubernetes/prescore-scheduler-config.yaml
            - --v=3
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          volumeMounts:
            - name: scheduler-config
              mountPath: /etc/kubernetes