service:
  type: ClusterIP
  port: 8080

deployment:
  image: coordination-service:0.1.0
  replicas: 1
  port: 80
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits: 
      memory: "128Mi"
      cpu: "500m"
