apiVersion: v1
kind: Namespace
metadata:
  name: minio-tenant
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio-kes
  namespace: minio-tenant
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
  namespace: minio-tenant
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: minio-kes
  namespace: minio-tenant
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-kes-secret
  namespace: minio-tenant
  annotations:
    kubernetes.io/service-account.name: minio-kes
type: kubernetes.io/service-account-token
