apiVersion: apps/v1
kind: Deployment
metadata:
  name: idmg-ml
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: image4
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: image4
  template:
    metadata:
      labels:
        app.kubernetes.io/name: image4
    spec:
      containers:
        - name: idmg-ml
          image: "{{ .Values.images.image4.repository }}:{{ .Values.images.image4.tag }}"
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
