apiVersion: apps/v1
kind: Deployment
metadata:
  name: idmg-db
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: image3
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: image3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: image3
    spec:
      containers:
        - name: idmg-db
          image: "{{ .Values.images.image3.repository }}:{{ .Values.images.image3.tag }}"
          env:
            {{- range .Values.images.image3.env }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
          imagePullPolicy: "{{ .Values.images.image3.imagePullPolicy }}"
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}

