apiVersion: apps/v1
kind: Deployment
metadata:
  name: idmgpl
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: idmgpl
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: idmgpl
  template:
    metadata:
      labels:
        app.kubernetes.io/name: idmgpl
    spec:
      containers:
        - name: idmgpl
          image: "{{ .Values.images.idmgpl.repository }}:{{ .Values.images.idmgpl.tag }}"
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
