# cf-idmg-ml-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: idmg-ml  # Unique service name for image1
spec:
  selector:  # Add this section
    app.kubernetes.io/name: image4  # Match deployment label
  ports:
  - protocol: TCP
    port: 80  # Service port (external)
    targetPort: 8080  # Maps to container port in deployment
  type: ClusterIP  # Internal communication within the cluster
