apiVersion: apps/v1
kind: Deployment
metadata:
  name: idmg-dc
  labels:
    app.kubernetes.io/name: image1
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: image1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: image1
    spec:
      containers:
        - name: idmg-dc
          image: "{{ .Values.images.image1.repository }}:{{ .Values.images.image1.tag }}"
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
