# templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-second-container-auth
stringData:
  username: {{ .Values.auth.username }}
  password: {{ .Values.auth.password }}