replicaCount: 1
images:
  image1:
    repository: idmg/cf
    tag: dc1
    imagePullPolicy: Always

  image2:
    repository: idmg/cf
    tag: custom-prescore-plugin

  image3:
    repository: idmg/cf
    tag: db5
    env:
      - name: NEO4J_USER
        value: neo4j
      - name: NEO4J_PSWD
        value: password
      - name: NEO4J_URL
        value: bolt://neo4j.idmg-scheduler-test.svc.cluster.local:7687
      - name: GENERATOR_URL
        value: http://idmg-dc.idmg-scheduler-test.svc.cluster.local/
    imagePullPolicy: Always

  image4:
    repository: idmg/cf
    tag: ml2
    env:
      - name: DB_API_URL
        value: http://idmg-db.idmg-scheduler-test.svc.cluster.local
    imagePullPolicy: Always

resources:
  requests:
    cpu: 1000m
    memory: 1024Mi
  limits:
    cpu: 1000m
    memory: 1024Mi
