# coding: utf-8

"""
    Data Sanitization Service

    This service implements an efficient and effective approach to protect users data by obfuscating information that can disclose their identities and sensitive information.

    The version of the OpenAPI document: 0.1.0
    Contact: seclab@unibg.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.job_api import router as JobApiRouter

app = FastAPI(
    title="Data Sanitization Service",
    description="This service implements an efficient and effective approach to protect users data by obfuscating information that can disclose their identities and sensitive information.",
    version="0.1.0",
)

app.include_router(JobApiRouter)
